// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AttrTest: typeof import('./src/components/AttrTest.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ReverseTable: typeof import('./src/components/ReverseTable.vue')['default']
    ReversTable: typeof import('./src/components/ReversTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideTable: typeof import('./src/components/SlideTable.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    Validate: typeof import('./src/components/Validate.vue')['default']
    ValidateInput: typeof import('./src/components/ValidateInput.vue')['default']
  }
}
